name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pint:
    name: Laravel Pint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run Laravel Pint
        run: vendor/bin/pint --test

  rector:
    name: Rector
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Rector
        run: vendor/bin/rector --no-progress-bar --dry-run
